name: 'Store variables'
description: 'Easily persist and read variables to reuse them between GitHub Action jobs'
branding:
  icon: bookmark
  color: red
inputs:
  variables:
    description: 'Write variable: `VAR=VALUE` | Read variable: `VAR`'
    required: true
  delimiter:
    description: 'Regex delimiter between each variable'
    required: false
    default: "\\r?\\n" # Regex splitting line with a '\n' or '\r'. They also need to be escaped, as they are special chars.
  failIfNotFound:
    description: "If true, will throw an error (and crash CI) when attempting to read a variable that doesn't exist in the store"
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'github-action-runtime/index.js'
