# Summary:
# Test if the GitHub Action builds correctly.
# Makes sure the GitHub Action builds when being built by GitHub Actions.
#
# See https://github.com/actions/checkout https://github.com/actions/checkout/releases/tag/v3

name: 'GitHub Action build test'
on:
  pull_request:
  push:

jobs:
  run-build-test:
    strategy:
      matrix:
        version: [ 18, 20 ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          yarn
          echo "Running yarn build:once"
          yarn build:once

          echo "Running yarn test:once"
          yarn test:once

          echo "Running yarn lint"
          yarn lint

          echo "Running yarn format:preview"
          yarn format:preview
